# Copyright 2024 General Atomics
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

context:
  version: ${{ env.get("PKG_VERSION") }}

package:
  name: toksearch_mast
  version: ${{ version }}

source:
  path: ..

build:
  script:
    - ${{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - setuptools
    - pip
    - versioneer
  run:
    - python
    - toksearch >=2.8.0
    - fdp >=0.2.1
    - fdp-schema >=0.1.2
    - xarray
    - zarr >=3
    - fsspec
    - s3fs
    - aiohttp

tests:
  - script:
      content:
        - python -c "import toksearch_mast"
    requirements:
      run:
        - fdp >=0.2.1

about:
  license: Apache-2.0
  summary: "TokSearch MAST: signal retrieval for MAST/MAST-U via FAIR MAST"

extra:
  recipe-maintainers:
    - sammuli
